spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          username: bigbaldy@163.com
          password:
          uri: https://github.com/bigbaldy1128/SpringCloud-Learning.git
          search-paths: config-repo/
server:
  port: 7001